apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
  labels:
    app: react-frontend-deployment
spec:
  selector:
    matchLabels:
      app: react-frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: react-frontend-deployment
    spec:
      containers:
        - name: topeducation-frontend-mysql
          image: aracelyu/react-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  selector:
    app: react-frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer